apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-version-app-deployment
  labels:
    app: go-version-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-version-app
  template:
    metadata:
      labels:
        app: go-version-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: go-version-app
          image: ghcr.io/brogrammer89/go-container-delivery-pipeline:634f20ba6cb53bc38016f8ad8bbf66d04f0dd7d5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
